# Generated by Django 3.1.2 on 2020-10-31 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201029_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='reference',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
