# Generated by Django 3.1.2 on 2020-11-01 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_list_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='files',
            field=models.FileField(default=django.utils.timezone.now, max_length=255, upload_to=''),
            preserve_default=False,
        ),
    ]
