# Generated by Django 3.1.2 on 2020-11-02 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_list_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='files',
        ),
        migrations.CreateModel(
            name='Listimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
                ('details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.list')),
            ],
        ),
    ]
