# Generated by Django 3.1.2 on 2020-11-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201102_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listimages',
            name='image',
            field=models.FileField(default='none', null=True, upload_to=''),
        ),
    ]
