# Generated by Django 3.1.2 on 2020-11-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201102_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='image',
            field=models.FileField(default='none', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Listimages',
        ),
    ]
